[package]
name        = "agnostik"
version     = "0.0.0"
description = "Einheit in Vielfalt. We unite everything with this software."
license     = "MIT"
authors     = ["Mahmut Bulut <vertexclique@gmail.com>"]
homepage    = "https://github.com/vertexclique"

[features]
runtime_bastion = [
    "bastion-executor"
]
runtime_asyncstd = [
    "async-std",
]
runtime_tokio = [
    "tokio"
]
runtime_nostd = [
    "core"
]

[dependencies]
bastion-executor = { version = "", optional = true, features = [] }
async-std = { version = "1.3", optional = true, features = ["unstable"] }
tokio = { version = "0.2", optional = true, features = ["rt-core", "blocking"] }
core = { package = "core-futures-tls", version = "0.1.0", optional = true }
